# -*- coding: utf-8 -*-
"""m03-projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UH57FeRYIQxDRBG6Msw8gue6L2I99Rep

# Sistema bancário

Crie uma lógica para simular o fluxo de um sistema bancário

Esse programa devará ter :

1. Um menu com seleção de operção

2. Criação de contas

3. Remoção de contas

5. Adicionar saldo / Remover saldo

6. Transferir valor entre contas

7. Consultar saldo de uma conta especifica:


As contas devem ser armazenadas em uma lista e cada conta deve ser um dicionário (chave valor) contendo as seguintes chaves :


1. Número_conta

2. Saldo-conta
"""

print(">>> Bem vindo ao  sistema <<<")
programa_ativo = True

while programa_ativo == True:
  print('\n### Menu ###')
  print("0 - Sair")
  numero_operção =input('Selecione a operção que desseja realizar:\n>>>')

  if numero_operção == "0":
    print('\nSistema encerrado.')
    programa_ativo = False

  else:
    print('\nOperção  inválida')

contas = []

def criar_conta():
  verificador_conta_existente = False
  dados_nova_conta = {}
  dados_nova_conta['numero_conta'] = input('Digite o número da nova conta:\n>>>')

  for conta_em_consulta in contas:
    if conta_em_consulta ['numero_conta'] == dados_nova_conta['numero_conta']:
      verificador_conta_exitente = True
    break

  if verificador_conta_existente == True:
    print('\nO númeroda conta ja existe. Tente novamente.')
  else:
    dados_nova_conta['saldo_conta'] = float(input('Digite o saldo da conta:\n>>>'))
    contas.append(dados_nova_conta)
    print('\nOperação efetuada com sucesso.')

def remover_conta():
  numero_conta = input('Digite o número da conta para remover:\n>>>')
  conta_encontrada = False
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      conta_encontrada = True
      contas.remove(conta_em_consulta)
      print('\nOperação efetuada com sucesso.')
      break
  if not conta_encontrada:
   print('\nO número da conta não existe. Tente novamente.')

def listar_contas():
  if len(contas) == 0:
    print('\nNão há contas cadastradas.')
  else:
    index = 1
    for conta_em_consulta in contas:
      if conta_em_consulta['saldo_conta'] >= 0:
        status_conta = 'Positivo'
      else:
        status_conta = 'Negativo'
      # format string - f string
      print(f"{index} - Número da conta: {conta_em_consulta['numero_conta']}\n")
      index += 1

def adicionar_saldo_em_conta():
  numero_conta = input('Digite o número da conta:\n>>>')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      valor_credito = float(input('Digite o valor do depósito:\n>>> R$'))
      if valor_credito < 0:
        print('\nValores negativos não são aceitos. Tente novamente.')
        return
      else:
        conta_em_consulta['saldo_conta'] += valor_credito
        print('\nOperação efetuada com sucesso.')
        return
  print('\nO número da conta não foi encontrado. Tente novamente.')

def remover_saldo_em_conta():
  numero_conta = input('Digite o número da conta:\n>>>')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      valor_debito = float(input('Digite o valor do débito:\n>>> R$'))
      if valor_debito < 0:
        print('\nValores negativos não são aceitos. Tente novamente.')
        return
      else:
        conta_em_consulta['saldo_conta'] -= valor_debito
        print('\nOperação efetuada com sucesso.')
        return
  print('\nO número da conta não foi encontrado. Tente novamente.')

def transferir_saldo_entre_contas():
  conta_partida = input('Digite o número da conta:\n>>>')
  verificador_etapa = 0
  # procura a primeira conta
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == conta_partida:
      verificador_etapa = 1
      conta_destino = input('Digite o número da conta destino:\n>>>')
      # verifique se é uma transferencia para a mesma conta
      if conta_destino != conta_partida:
        # procura a segunda conta
        for conta_destino_em_consulta in contas:
          if conta_destino_em_consulta['numero_conta'] == conta_destino:
            verificador_etapa = 3
            valor_transferencia = float(input('Digite o valor da transferência:\n>>> R$'))
            # verifica se o valor é negativo
            if valor_transferencia < 0:
              print('\nNão é possível transferir um valor negativo.')
              break
            # verifica se o saldo é suficiente
            elif valor_transferencia > conta_em_consulta['saldo_conta']:
              print('\nNão é ´possível transferir um valor maior que o seu saldo disponível.')
              break
            else:
              conta_em_consulta['saldo_conta'] -= valor_transferencia
              conta_destino_em_consulta['saldo_conta'] += valor_transferencia
              print('\nOperação efetuada com sucesso.')
              break

        print()
      else:
        verificador_etapa = 2
        break

  if verificador_etapa == 0:
    print('\nA conta não foi encontrado. Tente novamente.')
  elif verificador_etapa == 1:
    print('\nA conta de destino não foi encontrado. Tente novamente.')
  elif verificador_etapa == 2:
    print('\nNão é possível transferir dinheiro para a mesma conta.')

def Consultar_saldo_de_conta():
  numero_conta = input('Digite o numero da conta para consultar o saldo:\n>>> ')
  for conta_em_consulta in contas:
    if conta_em_consulta['numero_conta'] == numero_conta:
      if conta_em_consulta['saldo_conta'] >= 0:
          status_conta = 'Positivo'
      else:
        status_conta = 'Negativo'
      print(f"\nO saldo é: R$ {conta_em_consulta['saldo_conta']:.2f} ({status_conta})")
      return
  print('\nO número da conta não foi encontrado. Tente novamente.')

print(">>> Bem vindo ao sistema Banário <<<")

while True:
  print("\n### Menu ###")
  print("0 - Sair")
  print("1 - Criar uma nova conta")
  print("2 - Removver uma conta")
  print("3 - Listar todas as contas")
  print("4 - Adicionar saldo (creditar)")
  print("5 - Remover saldo (debitar)")
  print("6 - Transferir valor entre contas")
  print("7 - Consultar saldo de uma conta ")
  numero_operção = input('selecione a operação que deseja realizar:\n>>>')
  if numero_operção == "0":
    print('\nSistema encerrado.')
    break

  # operação 1 Criar uma nova conta
  elif numero_operção == "1":
    criar_conta ()

  # operação 2 - Remover conta
  elif numero_operção == "2":
    remover_conta()

  # operação 3 Listar todas as contas
  elif numero_operção == "3":
    listar_contas()

  # operação 4 - Adicionar saldo
  elif numero_operção == "4":
    adicionar_saldo_em_conta()

  # operação 5 - Remover saldo
  elif numero_operção == "5":
    remover_saldo_em_conta()

  # operação 6 - Transferir valor entre contas
  elif numero_operção == "6":
    transferir_saldo_entre_contas()

  # operação 7 - Consultar saldo de uma conta
  elif numero_operção == "7":
    Consultar_saldo_de_conta()

  #operação inválida
  else:
   print('\nOperação inválida.')